before_install:
  - gem update --system
  - gem --version
language: ruby
rvm:
  - ruby-head
  - 1.9.3
  - 1.8.7
  - ree
  - jruby
  - jruby-19mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head